### ISSUE TITLE
Configurar Github Action

### ISSUE THREAD

**Issue by nmarulo** [npedidos/rest-api#3]
Crear la carpeta `.github/workflows/` y el fichero `maven.yml` con la siguiente información:

```yml
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Compile with Maven
      run: mvn -B compile --file pom.xml
      
    - name: Test
      run: mvn -B test --file pom.xml
```

Además, agregar la configuración de deepsource para que se suba el reporte de cobertura de los test.

- Agregar la dependencia para generar el reporte: https://deepsource.io/docs/analyzer/test-coverage/#java
- Agregar la configuración de deepsource: https://deepsource.io/docs/analyzer/test-coverage/#with-github-actions-3
   - La variable de entorno `DEEPSOURCE_DSN` ya esta creada.
